### ISSUE TITLE
Question: does it support drag&drop of external objects, like files?

### ISSUE THREAD

**Issue by pfurini** [cuba-platform/cuba-dnd#2]
Can this component be used to handle the drag&drop of external objects?

I mean, using this to handle dropping a file over a control on the screen. 

I was thinking of a drop-in control to use with this component: [mariodavid/cuba-component-attachable](https://github.com/mariodavid/cuba-component-attachable), so that the user could either upload a file with the usual file browser dialog, OR simply drag&drop a file from the desktop to a control on the page.

**Comment by jreznot** [comment]
Hi,

Default FileUploadField of cuba component supports drop-zone attribute: https://doc.cuba-platform.com/manual-6.8/gui_FileUploadField.html#gui_FileUploadField_dropZone

**Comment by pfurini** [comment]
@jreznot Thanks for pointing out, I was not aware of that.. Do you think it's possible to extract the DropZone functionality to a stand-alone control, so we can use it outside of the FileUploadField control? It could be a better UX in some scenarios (a drop zone displayed directly in an entity screen for example).
Thx, P.

**Comment by jreznot** [comment]
> DropZone functionality to a stand-alone control, so we can use it outside of the FileUploadField control

DropZone - is a standalone control, you can use any VBoxLayout / HBoxLayout as dropZone with your FileUploadField / FileMultiUploadField. Or you can even you the entire Window as dropZone if you set it programmatically. Unfortunately, you cannot use it without FileUploadField since it handles uploading, you can try to hide it using CSS if it is really needed.

For statically shown dropZones you can use CSS classes: dropzone-container / dropzone-description . See com/haulmont/cuba/gui/app/core/file/file-upload-dialog.xml as the example.
